In [1]:
import sys
import os
sys.path.append(os.path.abspath('../'))

from src.utils import calculate_ranks, keep_highest_accuracy

In [2]:
results_location = '../data/results'

In [3]:
df_filtered = keep_highest_accuracy(f'{results_location}/clutad0/clusterddpm_results.json',
                     f'{results_location}/clutad0/clusterddpm_results_filtered.json')

In [ ]:

df = calculate_ranks(f'{results_location}/original_results/_results.json',
                     f'{results_location}/clutad0/clusterddpm_results_filtered.json',
                     'accuracy',
                     'ClusterDDPM',
                     f'{results_location}/final/detailed_acc_results.json')

In [5]:
df#.rename(columns={'accuracy': 'ClusterDDPM'})

,Data set ID,K-means(X),GMM(X),K-means(Z),GMM(Z),DEC,IDEC,DEPICT,DynAE,DCN,AE-CM,DKM,G-CEALS,ClusterDDPM
0,1063,80.300000,80.30000,68.000000,72.800000,67.000000,66.900000,66.100000,79.500000,80.300000,79.6000,79.600000,81.00000,79.500000
1,40994,52.400000,53.10000,57.000000,61.100000,57.000000,54.800000,50.400000,60.400000,64.600000,91.5000,60.000000,85.90000,91.500000
2,1510,91.200000,94.00000,92.100000,89.500000,91.400000,93.100000,93.700000,58.000000,77.700000,62.7000,80.200000,95.60000,95.300000
3,1480,61.400000,53.50000,64.000000,64.000000,59.300000,58.700000,62.100000,64.000000,63.700000,71.3000,65.800000,65.20000,68.400000
4,11,51.200000,52.60000,52.300000,55.800000,51.400000,52.300000,52.800000,51.700000,57.600000,46.1000,47.600000,69.30000,63.800000
5,37,66.100000,58.50000,73.200000,72.800000,71.400000,71.200000,67.400000,67.400000,64.400000,65.1000,66.400000,74.10000,64.700000
6,469,21.800000,21.50000,21.300000,21.600000,21.500000,21.300000,21.000000,22.300000,22.600000,20.5000,21.900000,22.00000,23.100000
7,458,98.200000,98.50000,83.600000,87.400000,81.500000,83.100000,78.800000,99.900000,51.000000,49.5000,64.500000,89.80000,50.100000
8,1464,68.300000,57.60000,73.900000,69.100000,66.400000,66.400000,56.100000,66.000000,74.100000,76.2000,64.300000,74.10000,76.200000
9,1068,89.200000,71.00000,92.300000,86.800000,82.500000,81.200000,59.000000,93.000000,93.000000,93.1000,93.100000,92.50000,93.100000
10,1049,81.900000,72.20000,84.300000,72.200000,70.000000,69.300000,66.500000,70.500000,87.100000,87.9000,87.500000,85.30000,87.800000
11,23,42.400000,39.60000,42.000000,43.400000,44.300000,43.800000,42.000000,38.800000,40.700000,42.7000,36.900000,44.20000,43.000000
12,1050,87.300000,75.00000,66.300000,76.200000,58.600000,62.500000,57.900000,89.700000,89.000000,89.7000,64.900000,83.00000,89.800000
13,40975,31.200000,31.20000,31.100000,34.700000,31.100000,31.100000,38.300000,46.100000,56.500000,70.0000,36.100000,49.20000,74.200000
14,40982,39.000000,37.50000,45.200000,46.100000,44.400000,44.800000,36.600000,47.600000,38.000000,36.6000,44.900000,41.30000,46.600000
15,1067,83.300000,72.60000,85.300000,77.000000,80.100000,79.300000,62.100000,77.300000,84.700000,84.7000,85.300000,85.20000,84.500000
16,Avg. rank,7.593750,8.96875,6.843750,6.531250,8.593750,8.843750,10.218750,6.687500,6.093750,6.3125,7.062500,3.53125,3.718750
17,Std. rank,2.550939,3.67636,2.908142,2.418462,2.933819,2.947987,3.326503,3.754442,3.536565,5.0129,3.673668,2.06130,3.582219
18,Overall rank,9.000000,12.00000,7.000000,5.000000,10.000000,11.000000,13.000000,6.000000,3.000000,4.0000,8.000000,1.00000,2.000000

In [6]:
df.drop(columns=['Data set ID']).round(1).rank(axis=1, ascending=False, method="min")

,K-means(X),GMM(X),K-means(Z),GMM(Z),DEC,IDEC,DEPICT,DynAE,DCN,AE-CM,DKM,G-CEALS,ClusterDDPM
0,2.0,2.0,10.0,9.0,11.0,12.0,13.0,7.0,2.0,5.0,5.0,1.0,7.0
1,12.0,11.0,8.0,5.0,8.0,10.0,13.0,6.0,4.0,1.0,7.0,3.0,1.0
2,8.0,3.0,6.0,9.0,7.0,5.0,4.0,13.0,11.0,12.0,10.0,1.0,2.0
3,10.0,13.0,5.0,5.0,11.0,12.0,9.0,5.0,8.0,1.0,3.0,4.0,2.0
4,11.0,6.0,7.0,4.0,10.0,7.0,5.0,9.0,3.0,13.0,12.0,1.0,2.0
5,9.0,13.0,2.0,3.0,4.0,5.0,6.0,6.0,12.0,10.0,8.0,1.0,11.0
6,6.0,8.0,10.0,7.0,8.0,10.0,12.0,3.0,2.0,13.0,5.0,4.0,1.0
7,3.0,2.0,6.0,5.0,8.0,7.0,9.0,1.0,11.0,13.0,10.0,4.0,12.0
8,7.0,12.0,5.0,6.0,8.0,8.0,13.0,10.0,3.0,1.0,11.0,3.0,1.0
9,8.0,12.0,7.0,9.0,10.0,11.0,13.0,4.0,4.0,1.0,1.0,6.0,1.0
10,7.0,8.0,6.0,8.0,11.0,12.0,13.0,10.0,4.0,1.0,3.0,5.0,2.0
11,7.0,11.0,8.0,4.0,1.0,3.0,8.0,12.0,10.0,6.0,13.0,2.0,5.0
12,5.0,8.0,9.0,7.0,12.0,11.0,13.0,2.0,4.0,2.0,10.0,6.0,1.0
13,9.0,9.0,11.0,8.0,11.0,11.0,6.0,5.0,3.0,2.0,7.0,4.0,1.0
14,9.0,11.0,4.0,3.0,7.0,6.0,12.0,1.0,10.0,12.0,5.0,8.0,2.0
15,7.0,12.0,1.0,11.0,8.0,9.0,13.0,10.0,4.0,4.0,1.0,3.0,6.0
16,5.0,2.0,7.0,9.0,4.0,3.0,1.0,8.0,11.0,10.0,6.0,13.0,12.0
17,11.0,3.0,8.0,12.0,8.0,8.0,7.0,2.0,6.0,1.0,3.0,13.0,5.0
18,5.0,2.0,7.0,9.0,4.0,3.0,1.0,8.0,11.0,10.0,6.0,13.0,12.0

In [ ]:

df = calculate_ranks(f'{results_location}/original_results/og_ari_results.json',
                     f'{results_location}/clutad0/clusterddpm_results_filtered.json',
                     'ari',
                     'ClusterDDPM',
                     f'{results_location}/final/detailed_acc_results.json')

In [8]:
df

,Data set ID,K-means(X),GMM(X),K-means(Z),GMM(Z),DEC,IDEC,DEPICT,DynAE,DCN,AE-CM,DKM,G-CEALS,ClusterDDPM
0,1063,0.044000,0.04400,0.127000,0.193000,0.115000,0.11200,0.10200,0.215000,0.192000,0.082000,0.007000,0.335000,0.000000
1,40994,0.001000,0.00300,0.017000,0.031000,0.017000,0.00900,-0.01000,0.006000,0.021000,0.000000,0.004000,0.029000,0.000000
2,1510,0.677000,0.77400,0.707000,0.620000,0.684000,0.74400,0.76200,0.020000,0.295000,0.000000,0.347000,0.831000,0.818398
3,1480,-0.072000,-0.03100,0.043000,0.031000,0.034000,0.02900,0.04800,0.031000,0.006000,-0.001000,-0.020000,0.033000,0.026338
4,11,0.139000,0.13500,0.140000,0.147000,0.130000,0.14000,0.12000,0.076000,0.097000,0.000000,0.083000,0.296000,0.264395
5,37,0.100000,0.01300,0.211000,0.205000,0.181000,0.17900,0.12100,0.110000,0.050000,0.000000,0.070000,0.200000,0.011912
6,469,0.004000,0.00300,0.007000,0.006000,0.007000,0.00700,0.00600,0.006000,0.009000,0.001000,0.006000,0.006000,0.014051
7,458,0.951000,0.95900,0.695000,0.766000,0.650000,0.70500,0.74700,0.996000,0.178000,0.060000,0.400000,0.786000,0.179280
8,1464,0.034000,-0.04800,0.077000,0.126000,0.061000,0.06600,0.01300,0.014000,0.009000,0.000000,0.024000,0.079000,0.000000
9,1068,0.184000,0.06000,0.157000,0.176000,0.105000,0.11000,0.02500,0.030000,0.080000,0.000000,0.014000,0.148000,0.000000
10,1049,0.090000,0.08000,0.049000,0.064000,0.055000,0.05600,0.09800,0.058000,0.051000,0.008000,0.011000,0.105000,0.000000
11,23,0.027000,0.00300,0.026000,0.032000,0.035000,0.03100,0.02700,-0.007000,0.018000,0.000000,-0.003000,0.033000,0.010493
12,1050,0.046000,0.11600,-0.048000,0.109000,-0.020000,-0.03300,0.02500,0.006000,0.060000,-0.000000,-0.057000,0.073000,0.000000
13,40975,0.013000,0.01300,0.011000,0.021000,0.011000,0.01100,0.01300,0.110000,0.021000,0.000000,0.029000,0.035000,0.276519
14,40982,0.156000,0.14200,0.217000,0.207000,0.218000,0.22100,0.12500,0.223000,0.082000,0.007000,0.192000,0.163000,0.165457
15,1067,0.209000,0.16200,0.185000,0.185000,0.218000,0.21800,0.05800,0.113000,0.119000,0.105000,0.179000,0.211000,0.000000
16,Avg. rank,6.968750,6.81250,6.312500,5.281250,6.281250,6.15625,7.65625,6.968750,7.750000,9.781250,8.562500,4.625000,7.843750
17,Std. rank,2.952224,3.05982,2.365551,2.190652,1.769828,1.63012,2.18875,3.073916,2.840188,2.489771,2.489143,2.179449,3.837181
18,Overall rank,7.000000,6.00000,5.000000,2.000000,4.000000,3.00000,9.00000,7.000000,10.000000,13.000000,12.000000,1.000000,11.000000